export const GET_POLICIES = 'GET_POLICIES';
export const ADD_POLICY = 'ADD_POLICY';
export const ADD_POLICY_TYPE = 'ADD_POLICY_TYPE';
export const RENDER_TYPE_UPDATE_FORM = 'RENDER_TYPE_UPDATE_FORM';
export const SELECT_POLICY_TYPE = 'SELECT_POLICY_TYPE';
export const UPDATE_POLICY_TYPE = 'UPDATE_POLICY_TYPE';